/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EAID_src6919CB_1734_44ef_BE5B_C115B637B2CD
 */
export type AdresseTilHusnummerSchema = string;
