/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * EAID_0E5C322B_0AA8_4005_B17E_F0397230EE7D
 */
export type AdresseTilEnhedBfeSchema = number[];
